### ISSUE TITLE
Unable to start activity ComponentInfo{com.jojo.design/com.jojo.design.module_core.ui.home.ACT_Home}: java.lang.IllegalStateException: properties.getProperty(name, defaultValue) must not be null

### ISSUE THREAD

**Issue by VinPin** [GraceJoJo/Designer#1]
readme中的apk，打开崩溃，崩溃日志：
Unable to start activity ComponentInfo{com.jojo.design/com.jojo.design.module_core.ui.home.ACT_Home}: java.lang.IllegalStateException: properties.getProperty(name, defaultValue) must not be null

Caused by: java.lang.IllegalStateException: properties.getProperty(name, defaultValue) must not be null
        at com.jojo.design.common_base.utils.BuildProperties.getProperty(BuildProperties.kt:45)
        at com.jojo.design.common_base.utils.StatusBarHelper.isMIUI(StatusBarHelper.kt:228)
        at com.jojo.design.common_base.utils.StatusBarHelper.setStatusTextColor(StatusBarHelper.kt:69)
        at com.jojo.design.module_core.ui.home.ACT_Home.switchFragment(ACT_Home.kt:110)
        at com.jojo.design.module_core.ui.home.ACT_Home.onCreate(ACT_Home.kt:50)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

是不是少了什么文件？不能这么放置的吧。

**Comment by GraceJoJo** [comment]
该问题已解决
