### ISSUE TITLE
老哥app打不开。。。报如下错误

### ISSUE THREAD

**Issue by yudengwei** [GraceJoJo/Designer#10]
Caused by: java.lang.IllegalStateException: properties.getProperty(name, defaultValue) must not be null
        at com.jojo.design.common_base.utils.BuildProperties.getProperty(BuildProperties.kt:45)
        at com.jojo.design.common_base.utils.StatusBarHelper.isMIUI(StatusBarHelper.kt:228)
        at com.jojo.design.common_base.utils.StatusBarHelper.setStatusTextColor(StatusBarHelper.kt:69)
        at com.jojo.design.module_core.ui.home.ACT_Home.switchFragment(ACT_Home.kt:110)
        at com.jojo.design.module_core.ui.home.ACT_Home.onCreate(ACT_Home.kt:50)

**Comment by JohnDwang** [comment]
都运行不了 没用

**Comment by GraceJoJo** [comment]
> 都运行不了 没用

是项目跑不起来？？？还是app运行不起来？提供一下手机型号和版本，我这边主流手机都是能正常运行的

**Comment by GraceJoJo** [comment]
> Caused by: java.lang.IllegalStateException: properties.getProperty(name, defaultValue) must not be null
> at com.jojo.design.common_base.utils.BuildProperties.getProperty(BuildProperties.kt:45)
> at com.jojo.design.common_base.utils.StatusBarHelper.isMIUI(StatusBarHelper.kt:228)
> at com.jojo.design.common_base.utils.StatusBarHelper.setStatusTextColor(StatusBarHelper.kt:69)
> at com.jojo.design.module_core.ui.home.ACT_Home.switchFragment(ACT_Home.kt:110)
> at com.jojo.design.module_core.ui.home.ACT_Home.onCreate(ACT_Home.kt:50)

是安装打开app就崩溃了吗？麻烦提供一下手机机型和Android版本

**Comment by GraceJoJo** [comment]
改问题已修复

**Comment by GraceJoJo** [comment]
该问题已修复好
